# Generated by Django 2.2.5 on 2019-09-24 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('data', models.DateField(default=datetime.date.today)),
                ('descripion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
